whitelisted_signers_map = [
  "messagingengine.com",
  "google.com",
  "microsoft.com",
  "icloud.com",
  "yahooinc.com",
  "proton.me",
  "protonmail.ch",
  "mailbox.org",
  "zoho.com",
  "forwardemail.net",
];
