---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: version
  image: syncloud/build-deps-arm
  commands:
  - echo $(date +%y%m%d)$DRONE_BUILD_NUMBER > version
  - echo arm$DRONE_BRANCH > domain

- name: build
  image: syncloud/build-deps-arm
  commands:
  - VERSION=$(cat version)
  - ./build.sh mail $VERSION

- name: test-intergation
  image: syncloud/build-deps-arm
  commands:
  - pip2 install -r dev_requirements.txt
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - DOMAIN=$(cat domain)
  - cd integration
  - py.test -x -s verify.py --domain=$DOMAIN --app-archive-path=$APP_ARCHIVE_PATH --device-host=device --app=mail



- name: upload
  image: syncloud/build-deps-arm
  commands:
  - VERSION=$(cat version)
  - PACKAGE=$(cat package.name)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload.sh mail $DRONE_BRANCH $VERSION $PACKAGE
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: artifact/*
    strip_components: 1
    target: /home/artifact/repo/mail/${DRONE_BUILD_NUMBER}-arm
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

services:
- name: device
  image: syncloud/platform-jessie-arm
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev


volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: dev
  host:
    path: /dev
- name: shm
  temp: {}

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: version
  image: syncloud/build-deps-amd64
  commands:
  - echo $(date +%y%m%d)$DRONE_BUILD_NUMBER > version
  - echo amd64$DRONE_BRANCH > domain

- name: build
  image: syncloud/build-deps-amd64
  commands:
  - VERSION=$(cat version)
  - ./build.sh mail $VERSION

- name: test-intergation
  image: syncloud/build-deps-amd64
  commands:
  - pip2 install -r dev_requirements.txt
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - DOMAIN=$(cat domain)
  - cd integration
  - py.test -x -s verify.py --domain=$DOMAIN --app-archive-path=$APP_ARCHIVE_PATH --device-host=device --app=mail

- name: test-ui-desktop
  image: syncloud/build-deps-amd64
  commands:
  - pip2 install -r dev_requirements.txt
  - DOMAIN=$(cat domain)
  - cd integration
  - py.test -x -s test-ui.py --ui-mode=desktop --domain=$DOMAIN --device-host=device --app=mail
  volumes:
  - name: shm
    path: /dev/shm

- name: test-ui-mobile
  image: syncloud/build-deps-amd64
  commands:
  - pip2 install -r dev_requirements.txt
  - DOMAIN=$(cat domain)
  - cd integration
  - py.test -x -s test-ui.py --ui-mode=mobile --domain=$DOMAIN --device-host=device --app=mail
  volumes:
  - name: shm
    path: /dev/shm

- name: upload
  image: syncloud/build-deps-amd64
  commands:
  - VERSION=$(cat version)
  - PACKAGE=$(cat package.name)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload.sh mail $DRONE_BRANCH $VERSION $PACKAGE
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: artifact/*
    strip_components: 1
    target: /home/artifact/repo/mail/${DRONE_BUILD_NUMBER}-amd64
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

services:
- name: device
  image: syncloud/platform-jessie-amd64
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev

- name: selenium
  image: selenium/standalone-firefox:4.0.0-beta-1-20210215
  volumes:
  - name: shm
    path: /dev/shm

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: dev
  host:
    path: /dev
- name: shm
  temp: {}

...
