---
kind: pipeline
name: amd64
platform:
  arch: amd64
  os: linux
services:
- image: syncloud/platform-bookworm-amd64:26.04.10
  name: mail.bookworm.com
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev
- image: syncloud/platform-buster-amd64:26.04.10
  name: mail.buster.com
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev
steps:
- commands:
  - echo $DRONE_BUILD_NUMBER > version
  image: debian:bookworm-slim
  name: version
- commands:
  - ./openssl/build.sh
  image: debian:bookworm-slim
  name: openssl
- commands:
  - ./openssl/test.sh
  image: debian:bookworm-slim
  name: openssl test
- commands:
  - ./nginx/build.sh
  image: debian:bookworm-slim
  name: nginx
- commands:
  - ./nginx/test.sh
  image: syncloud/platform-bookworm-amd64:26.04.10
  name: nginx test bookworm
- commands:
  - ./nginx/test.sh
  image: syncloud/platform-buster-amd64:26.04.10
  name: nginx test buster
- commands:
  - ./dovecot/build.sh
  image: debian:bookworm-slim
  name: dovecot
- commands:
  - ./dovecot/test.sh
  image: syncloud/platform-bookworm-amd64:26.04.10
  name: dovecot test bookworm
- commands:
  - ./dovecot/test.sh
  image: syncloud/platform-buster-amd64:26.04.10
  name: dovecot test buster
- commands:
  - ./opendkim/build.sh
  image: debian:bullseye-slim
  name: opendkim
- commands:
  - ./opendkim/test.sh
  image: syncloud/platform-bookworm-amd64:26.04.10
  name: opendkim test bookworm
- commands:
  - ./opendkim/test.sh
  image: syncloud/platform-buster-amd64:26.04.10
  name: opendkim test buster
- commands:
  - ./php/build.sh
  image: php:8.0.16-fpm-buster
  name: php
- commands:
  - ./php/test.sh
  image: syncloud/platform-bookworm-amd64:26.04.10
  name: php test bookworm
- commands:
  - ./php/test.sh
  image: syncloud/platform-buster-amd64:26.04.10
  name: php test buster
- commands:
  - ./postgresql/build.sh
  image: postgres:9.4-alpine
  name: postgresql
- commands:
  - ./postgresql/test.sh
  image: syncloud/platform-bookworm-amd64:26.04.10
  name: postgresql test bookworm
- commands:
  - ./postgresql/test.sh
  image: syncloud/platform-buster-amd64:26.04.10
  name: postgresql test buster
- commands:
  - ./postfix/build.sh
  image: debian:bookworm-slim
  name: postfix
- commands:
  - ./postfix/test.sh
  image: syncloud/platform-bookworm-amd64:26.04.10
  name: postfix test bookworm
- commands:
  - ./postfix/test.sh
  image: syncloud/platform-buster-amd64:26.04.10
  name: postfix test buster
- commands:
  - ./download.sh 1.6.1
  image: debian:bookworm-slim
  name: download
- commands:
  - ./cli/build.sh
  image: golang:1.24.0
  name: cli
- commands:
  - VERSION=$(cat version)
  - './package.sh mail $VERSION '
  image: debian:bookworm-slim
  name: package
- commands:
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - cd integration
  - ./deps.sh
  - py.test -x -s verify.py --distro=bookworm --domain=bookworm.com --app-archive-path=$APP_ARCHIVE_PATH
    --device-host=mail.bookworm.com --app=mail --arch=amd64
  image: python:3.12-slim-bookworm
  name: test bookworm
- commands:
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - cd integration
  - ./deps.sh
  - py.test -x -s verify.py --distro=buster --domain=buster.com --app-archive-path=$APP_ARCHIVE_PATH
    --device-host=mail.buster.com --app=mail --arch=amd64
  image: python:3.12-slim-bookworm
  name: test buster
- commands:
  - ./test/e2e/run.sh e2e specs/01-smoke.spec.ts desktop
  image: mcr.microsoft.com/playwright:v1.48.2-jammy
  name: e2e
- commands:
  - ./test/e2e/run.sh e2e specs/01-smoke.spec.ts mobile
  image: mcr.microsoft.com/playwright:v1.48.2-jammy
  name: e2e-mobile
- commands:
  - ./test/e2e/run.sh e2e-before-upgrade specs/02-pre-upgrade.spec.ts desktop
  image: mcr.microsoft.com/playwright:v1.48.2-jammy
  name: e2e-before-upgrade
- commands:
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - cd integration
  - ./deps.sh
  - py.test -x -s test-upgrade.py --distro=bookworm --domain=bookworm.com --app-archive-path=$APP_ARCHIVE_PATH
    --device-host=mail.bookworm.com --app=mail --arch=amd64
  image: python:3.12-slim-bookworm
  name: test-upgrade
- commands:
  - ./test/e2e/run.sh e2e-after-upgrade specs/03-post-upgrade.spec.ts desktop
  image: mcr.microsoft.com/playwright:v1.48.2-jammy
  name: e2e-after-upgrade
- commands:
  - PACKAGE=$(cat package.name)
  - apt update && apt install -y wget
  - wget https://github.com/syncloud/store/releases/download/4/syncloud-release-amd64
    -O release --progress=dot:giga
  - chmod +x release
  - ./release publish -f $PACKAGE -b $DRONE_BRANCH
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    SYNCLOUD_TOKEN:
      from_secret: SYNCLOUD_TOKEN
  image: debian:bookworm-slim
  name: upload
  when:
    branch:
    - stable
    - master
    event:
    - push
- commands:
  - apt update && apt install -y wget
  - wget https://github.com/syncloud/store/releases/download/4/syncloud-release-amd64
    -O release --progress=dot:giga
  - chmod +x release
  - ./release promote -n mail -a $(dpkg --print-architecture)
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    SYNCLOUD_TOKEN:
      from_secret: SYNCLOUD_TOKEN
  image: debian:bookworm-slim
  name: promote
  when:
    branch:
    - stable
    event:
    - push
- image: appleboy/drone-scp:1.6.4
  name: artifact
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source:
    - artifact/*
    strip_components: 1
    target: /home/artifact/repo/mail/${DRONE_BUILD_NUMBER}-amd64
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success
trigger:
  event:
  - push
type: docker
volumes:
- host:
    path: /var/run/dbus
  name: dbus
- host:
    path: /dev
  name: dev
---
kind: pipeline
name: arm64
platform:
  arch: arm64
  os: linux
services:
- image: syncloud/platform-bookworm-arm64:26.04.10
  name: mail.bookworm.com
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev
- image: syncloud/platform-buster-arm64:26.04.10
  name: mail.buster.com
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev
steps:
- commands:
  - echo $DRONE_BUILD_NUMBER > version
  image: debian:bookworm-slim
  name: version
- commands:
  - ./openssl/build.sh
  image: debian:bookworm-slim
  name: openssl
- commands:
  - ./openssl/test.sh
  image: debian:bookworm-slim
  name: openssl test
- commands:
  - ./nginx/build.sh
  image: debian:bookworm-slim
  name: nginx
- commands:
  - ./nginx/test.sh
  image: syncloud/platform-bookworm-arm64:26.04.10
  name: nginx test bookworm
- commands:
  - ./nginx/test.sh
  image: syncloud/platform-buster-arm64:26.04.10
  name: nginx test buster
- commands:
  - ./dovecot/build.sh
  image: debian:bookworm-slim
  name: dovecot
- commands:
  - ./dovecot/test.sh
  image: syncloud/platform-bookworm-arm64:26.04.10
  name: dovecot test bookworm
- commands:
  - ./dovecot/test.sh
  image: syncloud/platform-buster-arm64:26.04.10
  name: dovecot test buster
- commands:
  - ./opendkim/build.sh
  image: debian:bullseye-slim
  name: opendkim
- commands:
  - ./opendkim/test.sh
  image: syncloud/platform-bookworm-arm64:26.04.10
  name: opendkim test bookworm
- commands:
  - ./opendkim/test.sh
  image: syncloud/platform-buster-arm64:26.04.10
  name: opendkim test buster
- commands:
  - ./php/build.sh
  image: php:8.0.16-fpm-buster
  name: php
- commands:
  - ./php/test.sh
  image: syncloud/platform-bookworm-arm64:26.04.10
  name: php test bookworm
- commands:
  - ./php/test.sh
  image: syncloud/platform-buster-arm64:26.04.10
  name: php test buster
- commands:
  - ./postgresql/build.sh
  image: postgres:9.4-alpine
  name: postgresql
- commands:
  - ./postgresql/test.sh
  image: syncloud/platform-bookworm-arm64:26.04.10
  name: postgresql test bookworm
- commands:
  - ./postgresql/test.sh
  image: syncloud/platform-buster-arm64:26.04.10
  name: postgresql test buster
- commands:
  - ./postfix/build.sh
  image: debian:bookworm-slim
  name: postfix
- commands:
  - ./postfix/test.sh
  image: syncloud/platform-bookworm-arm64:26.04.10
  name: postfix test bookworm
- commands:
  - ./postfix/test.sh
  image: syncloud/platform-buster-arm64:26.04.10
  name: postfix test buster
- commands:
  - ./download.sh 1.6.1
  image: debian:bookworm-slim
  name: download
- commands:
  - ./cli/build.sh
  image: golang:1.24.0
  name: cli
- commands:
  - VERSION=$(cat version)
  - './package.sh mail $VERSION '
  image: debian:bookworm-slim
  name: package
- commands:
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - cd integration
  - ./deps.sh
  - py.test -x -s verify.py --distro=bookworm --domain=bookworm.com --app-archive-path=$APP_ARCHIVE_PATH
    --device-host=mail.bookworm.com --app=mail --arch=arm64
  image: python:3.12-slim-bookworm
  name: test bookworm
- commands:
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - cd integration
  - ./deps.sh
  - py.test -x -s verify.py --distro=buster --domain=buster.com --app-archive-path=$APP_ARCHIVE_PATH
    --device-host=mail.buster.com --app=mail --arch=arm64
  image: python:3.12-slim-bookworm
  name: test buster
- commands:
  - PACKAGE=$(cat package.name)
  - apt update && apt install -y wget
  - wget https://github.com/syncloud/store/releases/download/4/syncloud-release-arm64
    -O release --progress=dot:giga
  - chmod +x release
  - ./release publish -f $PACKAGE -b $DRONE_BRANCH
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    SYNCLOUD_TOKEN:
      from_secret: SYNCLOUD_TOKEN
  image: debian:bookworm-slim
  name: upload
  when:
    branch:
    - stable
    - master
    event:
    - push
- commands:
  - apt update && apt install -y wget
  - wget https://github.com/syncloud/store/releases/download/4/syncloud-release-arm64
    -O release --progress=dot:giga
  - chmod +x release
  - ./release promote -n mail -a $(dpkg --print-architecture)
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    SYNCLOUD_TOKEN:
      from_secret: SYNCLOUD_TOKEN
  image: debian:bookworm-slim
  name: promote
  when:
    branch:
    - stable
    event:
    - push
- image: appleboy/drone-scp:1.6.4
  name: artifact
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source:
    - artifact/*
    strip_components: 1
    target: /home/artifact/repo/mail/${DRONE_BUILD_NUMBER}-arm64
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success
trigger:
  event:
  - push
type: docker
volumes:
- host:
    path: /var/run/dbus
  name: dbus
- host:
    path: /dev
  name: dev
---
kind: pipeline
name: arm
platform:
  arch: arm
  os: linux
services:
- image: syncloud/platform-bookworm-arm:26.04.10
  name: mail.bookworm.com
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev
- image: syncloud/platform-buster-arm:26.04.10
  name: mail.buster.com
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev
steps:
- commands:
  - echo $DRONE_BUILD_NUMBER > version
  image: debian:bookworm-slim
  name: version
- commands:
  - ./openssl/build.sh
  image: debian:bookworm-slim
  name: openssl
- commands:
  - ./openssl/test.sh
  image: debian:bookworm-slim
  name: openssl test
- commands:
  - ./nginx/build.sh
  image: debian:bookworm-slim
  name: nginx
- commands:
  - ./nginx/test.sh
  image: syncloud/platform-bookworm-arm:26.04.10
  name: nginx test bookworm
- commands:
  - ./nginx/test.sh
  image: syncloud/platform-buster-arm:26.04.10
  name: nginx test buster
- commands:
  - ./dovecot/build.sh
  image: debian:bookworm-slim
  name: dovecot
- commands:
  - ./dovecot/test.sh
  image: syncloud/platform-bookworm-arm:26.04.10
  name: dovecot test bookworm
- commands:
  - ./dovecot/test.sh
  image: syncloud/platform-buster-arm:26.04.10
  name: dovecot test buster
- commands:
  - ./opendkim/build.sh
  image: debian:bullseye-slim
  name: opendkim
- commands:
  - ./opendkim/test.sh
  image: syncloud/platform-bookworm-arm:26.04.10
  name: opendkim test bookworm
- commands:
  - ./opendkim/test.sh
  image: syncloud/platform-buster-arm:26.04.10
  name: opendkim test buster
- commands:
  - ./php/build.sh
  image: php:8.0.16-fpm-buster
  name: php
- commands:
  - ./php/test.sh
  image: syncloud/platform-bookworm-arm:26.04.10
  name: php test bookworm
- commands:
  - ./php/test.sh
  image: syncloud/platform-buster-arm:26.04.10
  name: php test buster
- commands:
  - ./postgresql/build.sh
  image: postgres:9.4-alpine
  name: postgresql
- commands:
  - ./postgresql/test.sh
  image: syncloud/platform-bookworm-arm:26.04.10
  name: postgresql test bookworm
- commands:
  - ./postgresql/test.sh
  image: syncloud/platform-buster-arm:26.04.10
  name: postgresql test buster
- commands:
  - ./postfix/build.sh
  image: debian:bookworm-slim
  name: postfix
- commands:
  - ./postfix/test.sh
  image: syncloud/platform-bookworm-arm:26.04.10
  name: postfix test bookworm
- commands:
  - ./postfix/test.sh
  image: syncloud/platform-buster-arm:26.04.10
  name: postfix test buster
- commands:
  - ./download.sh 1.6.1
  image: debian:bookworm-slim
  name: download
- commands:
  - ./cli/build.sh
  image: golang:1.24.0
  name: cli
- commands:
  - VERSION=$(cat version)
  - './package.sh mail $VERSION '
  image: debian:bookworm-slim
  name: package
- commands:
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - cd integration
  - ./deps.sh
  - py.test -x -s verify.py --distro=bookworm --domain=bookworm.com --app-archive-path=$APP_ARCHIVE_PATH
    --device-host=mail.bookworm.com --app=mail --arch=arm
  image: python:3.12-slim-bookworm
  name: test bookworm
- commands:
  - APP_ARCHIVE_PATH=$(realpath $(cat package.name))
  - cd integration
  - ./deps.sh
  - py.test -x -s verify.py --distro=buster --domain=buster.com --app-archive-path=$APP_ARCHIVE_PATH
    --device-host=mail.buster.com --app=mail --arch=arm
  image: python:3.12-slim-bookworm
  name: test buster
- commands:
  - PACKAGE=$(cat package.name)
  - apt update && apt install -y wget
  - wget https://github.com/syncloud/store/releases/download/4/syncloud-release-arm
    -O release --progress=dot:giga
  - chmod +x release
  - ./release publish -f $PACKAGE -b $DRONE_BRANCH
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    SYNCLOUD_TOKEN:
      from_secret: SYNCLOUD_TOKEN
  image: debian:bookworm-slim
  name: upload
  when:
    branch:
    - stable
    - master
    event:
    - push
- commands:
  - apt update && apt install -y wget
  - wget https://github.com/syncloud/store/releases/download/4/syncloud-release-arm
    -O release --progress=dot:giga
  - chmod +x release
  - ./release promote -n mail -a $(dpkg --print-architecture)
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    SYNCLOUD_TOKEN:
      from_secret: SYNCLOUD_TOKEN
  image: debian:bookworm-slim
  name: promote
  when:
    branch:
    - stable
    event:
    - push
- image: appleboy/drone-scp:1.6.4
  name: artifact
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source:
    - artifact/*
    strip_components: 1
    target: /home/artifact/repo/mail/${DRONE_BUILD_NUMBER}-arm
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success
trigger:
  event:
  - push
type: docker
volumes:
- host:
    path: /var/run/dbus
  name: dbus
- host:
    path: /dev
  name: dev
