dovecot_config_version = 2.4.4
dovecot_storage_version = 2.4.4

base_dir = {{ .DataDir }}/dovecot/
import_environment = TZ CORE_OUTOFMEM CORE_ERROR PATH LD_LIBRARY_PATH

protocols {
  imap = yes
  pop3 = yes
  lmtp = yes
}

mail_driver = maildir
mail_path = {{ .DataDir }}/box/%{user}
mail_uid = dovecot
mail_gid = dovecot

postmaster_address = postmaster@{{ .DeviceDomainName }}

namespace inbox {
  inbox = yes

  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Trash {
    special_use = \Trash
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
}

auth_mechanisms {
  plain = yes
  login = yes
}

passdb ldap {
  ldap_uris = ldap://localhost
  ldap_auth_dn = dc=syncloud,dc=org
  ldap_auth_dn_password = syncloud
  ldap_version = 3
  ldap_base = ou=users,dc=syncloud,dc=org
  ldap_scope = subtree
  passdb_ldap_bind = yes
  passdb_ldap_bind_userdn = cn=%{user},ou=users,dc=syncloud,dc=org
  passdb_ldap_filter = (&(objectClass=inetOrgPerson)(cn=%{user}))
}

userdb static {
  fields {
    uid = dovecot
    gid = dovecot
    home = {{ .DataDir }}/box/%{user}
  }
}

ssl = yes
ssl_min_protocol = TLSv1.2

ssl_server {
  cert_file = /var/snap/platform/current/syncloud.crt
  key_file = /var/snap/platform/current/syncloud.key
}

service imap-login {
  user = mail
  inet_listener imap {
  }
  inet_listener imaps {
  }
}

service pop3-login {
  user = mail
  inet_listener pop3 {
  }
  inet_listener pop3s {
  }
}

service lmtp {
  unix_listener private/dovecot-lmtp {
    mode = 0600
  }
}

service imap {
}

service pop3 {
}

service auth {
  unix_listener auth-userdb {
    mode = 0777
    user = dovecot
    group = dovecot
  }
  unix_listener private/auth {
    mode = 0777
    user = dovecot
    group = dovecot
  }
}

service auth-worker {
}

protocol lda {
  mail_plugins {
    sieve = yes
  }
}

sieve_script spam {
  sieve_script_type = before
  sieve_script_driver = file
  sieve_script_file_path = {{ .DataDir }}/config/sieve/spam.sieve
}
