AutoRestart             Yes
AutoRestartRate         10/1h
UMask                   002
Syslog                  yes
SyslogSuccess           Yes
LogWhy                  Yes

Canonicalization        relaxed/simple

ExternalIgnoreList      refile:{{ .DataDir }}/config/opendkim/TrustedHosts
InternalHosts           refile:{{ .DataDir }}/config/opendkim/TrustedHosts
KeyTable                refile:{{ .DataDir }}/config/opendkim/KeyTable
SigningTable            refile:{{ .DataDir }}/config/opendkim/SigningTable

Mode                    sv
PidFile                 {{ .DataDir }}/opendkim.pid
SignatureAlgorithm      rsa-sha256

UserID                  mail:mail

Socket                  local:{{ .DataDir }}/opendkim.socket

