unixsocket {{ .DataDir }}/redis/redis.sock
unixsocketperm 770
port 0
daemonize no
pidfile {{ .DataDir }}/redis/redis.pid
dir {{ .DataDir }}/redis
dbfilename dump.rdb
logfile {{ .DataDir }}/log/redis.log
save 900 1
appendonly no
maxmemory 64mb
maxmemory-policy volatile-lru
